CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_type VARCHAR(32) NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(120),
  phone VARCHAR(40),
  service VARCHAR(64),
  message TEXT,
  bioevolva_user BOOLEAN NOT NULL DEFAULT FALSE,
  bioevolva_email VARCHAR(255),
  source VARCHAR(64),
  utm_source VARCHAR(128),
  utm_medium VARCHAR(128),
  utm_campaign VARCHAR(128),
  consented_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_leads_type_created ON leads (lead_type, created_at DESC);
CREATE INDEX idx_leads_email ON leads (email);
